### ISSUE TITLE
Suggestion: don't colorize

### ISSUE THREAD

**Issue by rauchg** [zeit/hyperlinks#1]
Since the regexp is so eager (due to how many different TLDs there are), we should probably err on the side of caution.

Let's not colorize by default, and just display underline upon hover?

**Comment by nkzawa** [comment]
👍 makes sense.

**Comment by IanMitchell** [comment]
Would it be better to tone the regex back a bit perhaps? Maybe require an `http://` at the front? This also would prevent false positives in directory listings such as the following
```
/Users/ian/Sites/ianmitchell.io/_config.yml
=> ianmitchell.io/_config.yml
```

**Comment by rauchg** [comment]
@IanMitchell that's a very good idea. If we do `https?` we can preserve the colorization too (which I like) :D

Reading a config option `hyperlinkColor` would be nice in case people want to customize it.

**Comment by IanMitchell** [comment]
Yeah, I agree - I prefer the colorization as well, but having an option to disable/customize it would be great!

**Comment by nkzawa** [comment]
about styles, you can customize it by changing `termCss` in your `.hypertems.js`

```js
termCSS: `
  x-screen a {
    color: red;
  }
  x-screen a.hover {
    text-decoration: none;
  }
`,

```

**Comment by rauchg** [comment]
Awesome :) Would be great to have that on the README.

**Comment by nkzawa** [comment]
Closed via https://github.com/zeit/hyperlinks/commit/72e2201339715e903ba47240ff30937606a6c2f2
