### ISSUE TITLE
Switch CMD + Click

### ISSUE THREAD

**Issue by vinkla** [zeit/hyperlinks#15]
The default behaviour is to open the links within the application. Maybe it would be better to open the links in the default browser and `cmd + click` if the user wants to open the link within Hyper?

IMO it feels more natural to open the link in my default browser. What is your opinion?

**Comment by taylorthurlow** [comment]
I agree. While the in-application browser feature is cool, I would use it less than I would my actual browser.

**Comment by vors** [comment]
+1 for that. It especially hurts, because `Ctrl+C` to cancel the window is unconventional and kind of cryptic. Adding `Esc` as an alternative would somewhat help.

**Comment by vutran** [comment]
+1 on this as well. I hate losing my terminal log as the current behavior clicks through to the URL with no way to go back (ref #2)

**Comment by luisrudge** [comment]
👍

**Comment by kaicataldo** [comment]
Adding to this, I'd actually love to have the ability to configure it so that I can turn off opening links in Hyper entirely.

**Comment by nkzawa** [comment]
The current default behavior is changed like this.

**Comment by vinkla** [comment]
:+1:
