### ISSUE TITLE
Enhancement: Open chrome devtools links `chrome-devtools://`

### ISSUE THREAD

**Issue by dbo** [zeit/hyperlinks#18]
Would be very convenient to be able to open debug links (`node --inspect ...`, schema `chrome-devtools`).

**Comment by wesbos** [comment]
Just came here to open this issue - 

![](http://wes.io/iUcI/content)

Here is a URL :`chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/386535ba-f264-4987-afa6-9b32dcce7d04 `

**Comment by dbo** [comment]
The url-regexp is slightly wrong, and needs to explicitly cover `devtools` in the host part. When fixing that I could hover/click the URL, but apparently neither Chrome/OSX (via `shell.openExternal`) nor meta+open opens the URL.

```bash
$ open -a 'Google Chrome' 'chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d231...'
The file /Users/.../chrome-devtools:/devtools/remote/serve_file/@60cd6e...ctor.html?experiments=true does not exist.
```

opening via
```bash
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome 'chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d231...'
```
opens an empty page.

**Comment by alexdrans** [comment]
Anyone figured this out yet? @dbo is correct, it's tricky to open devtools from the CLI.

**Comment by ArnaudRinquin** [comment]
@alexdrans I came here looking for the same thing. It seems impossible to open `chrome-devtools` from a link, probably for security reasons, but only by pasting the url in the URL bar.

I'll open an issue on node so there is a way to disable the random bit of the url so we can simply reload the chrome dev tools.

**Comment by wesbos** [comment]
I've been using this extension which added automatic refreshing:

https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en

**Comment by june07** [comment]
https://june07.com/blog/inspect-broke-my-workflow/
