### ISSUE TITLE
Wrapping links only include the first line

### ISSUE THREAD

**Issue by awayken** [zeit/hyperlinks#20]
If I have a long link that wraps in my prompt, Hyperlinks makes the first line into a hyperlink but doesn't include the content on the second line.

![image](https://cloud.githubusercontent.com/assets/156215/21188886/6a88c880-c1e2-11e6-9134-6462fea16ef3.png)

I'm using Hyper 1.0.0 on Windows 10 if that matters.

**Comment by wesbos** [comment]
Running into this issue too :(

**Comment by bloqhead** [comment]
I was running into this and then it just randomly fixed itself...

This is my PS1: `export PS1="\[$(tput bold)\]\[$(tput setaf 2)\][\u]\[$(tput sgr0)\] \[$(tput setaf 4)\]in \w\[$(tput sgr0)\] \[$(tput setaf 5)\]\`prompt_vcs\` $\[$(tput sgr0)\] "`

**Comment by wopian** [comment]
Same with Hyper 1.3.1 on W10. It's particularly annoying with a narrow terminal

**Comment by rzeigler** [comment]
Also an issue in 1.3.3 on macOS. Seems to be recurring of #6.

**Comment by mrpinkcat** [comment]
Same here :/ Any way to fix this ?
