### ISSUE TITLE
Indentation in vim

### ISSUE THREAD

**Issue by rastasheep** [zeit/hyperlinks#4]
After enabling this plugin my vim looses indentation. Rendering of indented code is wrong, all intentions are missing. When i select whole file, that triggers re-render and intention is back. I've tried on multiple files, and situation is the same.

For indentation in vim i'm using spaces, if that means anything for reproducing this.
Also i'm not using custom css for plugin as suggested in Readme.

Here is dev console status
![screen shot 2016-07-26 at 8 23 17 pm](https://cloud.githubusercontent.com/assets/695790/17150265/0683215a-536f-11e6-80c8-65c4670f18e5.png)
(notice how text is not indented on the left side of the screen)

**Comment by bmcallis** [comment]
I have the same issue, it seems to have something to do with line numbers. If I open a file without using my vimrc `the indentation seems correct.

**Comment by rastasheep** [comment]
I can confirm that this issue is related with line numbers, when i turn them off indentation is fine.

**Comment by nkzawa** [comment]
Umm, I can't reproduce. 
Do you mean `set number` in your `.vimrc` causes the issue ?

**Comment by demands** [comment]
I can confirm: with `hyperlinks` enabled, and `set number` enabled in vim, my indentation is 100% broken. :(

**Comment by flaviocamilo** [comment]
I can reproduce this. Using `Hyper 1.1.0` with `hyperlinks 0.4.0`.
Disabling `Vim` line numbers avoids the problem.

**Comment by 616b2f** [comment]
Same issue here Hyper v1.3.1 (in neovim v0.1.7)

With hyperlink:
<img width="749" alt="screen shot 2017-04-19 at 19 14 07" src="https://cloud.githubusercontent.com/assets/7147208/25192785/e0c55cf6-2534-11e7-85fa-e247a0376278.png">

without:
![image](https://cloud.githubusercontent.com/assets/7147208/25192769/d27936e0-2534-11e7-99da-9e991d798366.png)

**Comment by emredjan** [comment]
Same here, can reproduce with hyper 1.3.2, hyperlinks 0.5.0, nvim 0.2.0

**Comment by mtslzr** [comment]
Running Hyper 1.4.8 with neovim. Same issue here still.
