### ISSUE TITLE
Support file paths

### ISSUE THREAD

**Issue by AndersDJohnson** [zeit/hyperlinks#43]
Not sure how to detect reliably, but iTerm 2 does it. Maybe any token that starts with `/` or has a `/` or at least some minimum number of `/`s or has `/` and last part has any `.`.

Could open with [`opn`](https://www.npmjs.com/package/opn).

**Comment by Wizek** [comment]
I'm also looking for this. `Terminator` is able to do this as well. Any news?

Also, a related issue: https://github.com/zeit/hyper/issues/413
