### ISSUE TITLE
Possible problem with port numbers

### ISSUE THREAD

**Issue by whyboris** [zeit/hyperlinks#44]
For example the link I have is `http://127.0.0.1:8080`
But when I click on it, the browser opens to `http://127.0.0.1`

It looks like https://github.com/zeit/hyperlinks/blob/master/url-regex.js#L11 has the support for ports, but somehow it failed in my case.

Should the line be changed from this:
`const port = '(?::\\d{2,5})?';` to this:
`const port = '(?::\d{2,5})?';` ?

Port number did work in another scenario. I'm suspecting this problem may be arising because in the case where it doesn't work, the port is a different color, so the terminal may be doing something fancy in the background (maybe wrapping text in special prefixes to color-code them).

**Comment by alexanderchan** [comment]
Saw this in create-react-app, there is a bold on the port number.  This causes multiple rows to be created and I think hyperlinks is looking at the row and not looking at adjacent rows for the text content:

Below we can see that the port is then being split to a different row. 

![image](https://user-images.githubusercontent.com/1864372/29791999-3cce0326-8bfc-11e7-8bba-3ca840da271b.png)

We can see that the regex works when if you echo 'http://test.com:3000' on the console.

But that a js program causes the same missing port:

```javascript
var chalk = require("chalk");
console.log("http://test.com:" + chalk.bold("3000"));
```

**Comment by alexanderchan** [comment]
The issue I'm describing is #25, not sure if yours is the same @whyboris

**Comment by whyboris** [comment]
@alexanderchan -- I suspect that may be the issue 👍

**Comment by imshuffling** [comment]
Any joy on a solution or workaround for this?

**Comment by Maxhodges** [comment]
same problem with gatsbyjs. the build process spits out a url but hyperlink ignores the port
![image](https://user-images.githubusercontent.com/957271/38793297-aa83706e-418b-11e8-94a8-630e86e4e8c4.png)

**Comment by Maxhodges** [comment]
![image](https://user-images.githubusercontent.com/957271/38793410-253b05d8-418c-11e8-95b0-251d0ed67487.png)

**Comment by Maxhodges** [comment]
guess there is nothing you can do about that!

**Comment by imshuffling** [comment]
Yeah same problem, annoying.

**Comment by Maxhodges** [comment]
weird, so is this problem CAUSED by Hyper?

 I suspect your terminal is splitting the url and highlighting it incorrectly because here is the line from gatsby which outputs the url shown in the above screenshots:

https://github.com/gatsbyjs/gatsby/blob/8680988fc922186c2d52f80ab6acb6e935fd4ebf/packages/gatsby/src/commands/develop.js#L349

**Comment by whyboris** [comment]
*Hyper* 2.0.0 is out just 1 hour ago: https://github.com/zeit/hyper/releases/tag/2.0.0
Perhaps this will no longer be an issue 👍

**Comment by Maxhodges** [comment]
awesome possum, works for me!
![image](https://user-images.githubusercontent.com/957271/38823607-cdba0948-41e1-11e8-9eee-12861dc84906.png)
