### ISSUE TITLE
Configuration is not applied

### ISSUE THREAD

**Issue by just-boris** [zeit/hyperlinks#46]
I have the following content of my `~/.hyper.js` file 

```js
module.exports = {
  config: {

    // font-size, css, etc, omitted

    hyperlinks: {
      clickAction: 'ignore',
      defaultBrowser: false
    }
  },

  plugins: [
    "hyperlinks"
  ]
};
```

But my settings have no effect for the terminal. When I opened devtools and stopped at breakpoint [here](https://github.com/zeit/hyperlinks/blob/master/index.js#L33), it says, that `window.config.getConfig().hyperlinks` is not defined.

Have I missed anything? How should I configure the plugin?

I am using `Hyper 1.4.8 (stable)` on Mac

**Comment by cpheimbach** [comment]
It seems I have the same issue. Haven't tried out the breakpoints but as soon as I am adding hyperlinks to the config object it even stops working.

**Comment by colinrcummings** [comment]
I've found that they're only applied to the first terminal session--either a new window or tab; it's lost as soon as you split vertically or horizontally.
