### ISSUE TITLE
Link files?

### ISSUE THREAD

**Issue by ericclemmons** [zeit/hyperlinks#5]
iTerm2 does a good job of linking paths, which is extremely useful when jumping from lint errors to the default editor:

``` shell
$ eslint src
/path/to/src/server.js
  54:3  error  All 'var' declarations must be at the top of the function scope  vars-on-top
```

Thoughts?

**Comment by nkzawa** [comment]
It seems very useful, but maybe we should create it as a different plugin ?
This plugin makes all urls clickable without any user actions, but we wouldn't like to do that for paths (e.g., stdout of `find` and `ls`).

**Comment by kartsims** [comment]
Could it be a plugin option ? "hyperlinks" seems like a good plugin name to create links even if it is links to local files... Option could be enabled by default IMO

Problem could be when using terminal to browse remote server.

**Comment by ericclemmons** [comment]
Funny, none of these scenarios were even noticeable when I used iTerm2...

**Comment by uetchy** [comment]
How about adding keyboard action (while pushing `ctrl`) to activate filepath linking?

**Comment by ericclemmons** [comment]
@uetchy I think that's very fair.  Ctrl on windows & Cmd on Mac, IIRC, is common.

I guess the question was, _will a PR that satisfies this be accepted_, or no?

**Comment by MoOx** [comment]
> will a PR that satisfies this be accepted?

+1 for this question :)

**Comment by PatNeedham** [comment]
@ericclemmons did you find a way to open local files by clicking?
