### ISSUE TITLE
Doesn't work at all? 

### ISSUE THREAD

**Issue by wesbaker** [zeit/hyperlinks#7]
I'm likely doing something wrong here, but links are not clickable for me when holding the Command key. I've added `hyperlinks` to my plugins list and I can see it in under `~/.hyperterm_plugins/node_modules/` and no links are clickable. Is there anything else I need to do?

**Comment by kartsims** [comment]
Same here, with version `0.7.1.36`

**Comment by nkzawa** [comment]
It woks fine to me with hyperterm v0.7.1.36.

```
$ # https://hyperterm.org
``` 

What happens when you type like the above ?  It should add color to the url and should be clickable.

**Comment by kartsims** [comment]
Just tested again and it is working now... weird... I swear I reloaded HyperTerm, and even restarted it...

I guess we could close the issue if ever @wesbaker doesn't have the issue anymor either.

**Comment by wesbaker** [comment]
> What happens when you type like the above ? It should add color to the url and should be clickable.

It adds color, but it's still not clickable:

![screen shot 2016-08-29 at 10 03 29 am](https://cloud.githubusercontent.com/assets/15715/18053931/b6679b44-6dcf-11e6-83c5-441893a2feb4.png)

I'm using Hyperterm 0.7.1.36:

![screen shot 2016-08-29 at 10 03 49 am](https://cloud.githubusercontent.com/assets/15715/18053937/bf19a9ee-6dcf-11e6-80fa-868dba3718da.png)

I've done a full reload and quit and restarted with no luck. Could it be another plugin causing problems? I don't have many, but here's what I have:

```
plugins: [
  'hyperterm-atom-dark',
  'hyperterm-1password',
  'hyperterm-subpixel-antialiased',
  'hypercwd',
  "hyperlinks"
],
```

**Comment by capaj** [comment]
works for me, but I only have `hyperlinks` in my plugins

**Comment by ericmarkmartin** [comment]
Works for me, but just typing `now.sh` as they do in the video at hyper.is doesn't work for me.

**Comment by jsdnxx** [comment]
also not working for me, hyper Version 0.8.3 (0.8.3.873) after an app restart

**Comment by TsundereBug** [comment]
Not working for me when I alt+click on windows.

Config: [b29a000d1e2c67b679412c45c977f349](https://gist.github.com/TsundereBug/b29a000d1e2c67b679412c45c977f349)

**Comment by danmindru** [comment]
### Update
> using `Hyper 2.0.4 (canary)`

Link coloring does work, but alt+click tries downloading `download.html` (which does contain a snapshot of the site I've tried to access).

**Comment by capaj** [comment]
yeah I haven't user hyperterm in a while. Haven't had time to update this plugin. Will mark as broken in the readme.

**Comment by DanielTamkin** [comment]
hyperlinks doesn't even build for the latest version of Hyper (1.4.8). Upon further inspection DevTools says that there is no package.json associated with the plugin.


![image](https://user-images.githubusercontent.com/9532762/36442935-ee1029f0-163c-11e8-98b7-a5354e11599c.png)

**Comment by lacymorrow** [comment]
It seems like this project has little to no maintenance or direction, seeing as how the top issue from over 18 months ago reads: "Doesn't work at all?".

Lets be real; I need my terminal hyperlinks as much as I need highlight-to-copy. They're essential shortcuts and completely wreck my workflow if I can't use them.
I need Hyperterm to be as functional as iTerm3.

It's time for a community fork, or - as it's MIT-licensed - a complete rewrite.
I'll see if I have time next week.

**Comment by lacymorrow** [comment]
From the Devs:

Hi @lacymorrow, hyperlinks will be deprecated with Hyper v2 release.
Links are now handled directly by xtermjs in our canary release and you don't need any plugin to handle them.

Do not hesitate to open an issue in zeit/hyper if you encounter some problems with this canary functionality.

Thanks to xterm the canary channel is also way faster and better at handling large output. So it's highly recommended to upgrade. Here's how to upgrade: zeit.co/blog/canary#hyper

The Hyperlinks repository will be deprecated and archived when v2 comes out officially (very soon).

**Comment by SirWindfield** [comment]
@lacymorrow @wesbaker Looks like highlighting doesn't work in v2 though.

**Comment by bboure** [comment]
@lacymorrow thanks for clarification.
in Hyper v2 I can click on a link and it gets open into the default browser.
However, what about the nice features this plugin had? Like open urls embedded into the terminal using the meta key?

**Comment by bboure** [comment]
Sorry @lacymorrow, found an answer here: https://github.com/zeit/hyper/issues/2748
